---
- name: authorised keys
  hosts: all

  tasks:
    - name: auth login from your key
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '../authorised-keys/your-key.pub') }}"
